### ISSUE TITLE
Solving Large Laplacian Problems

### ISSUE THREAD

**Issue by RoyiAvital** [dylanswiggett/image-matting#1]
Thank you for this great writing and code.

I was wondering, which method was best for matting?
What about the best solver?

Have you looked at Efficient Preconditioning of Laplacian Matrices for Computer Graphics (http://www.cs.huji.ac.il/~raananf/projects/hsc/)?

**Comment by dylanswiggett** [comment]
Hi Royi,

Thanks for your interest in my project! I only implemented the V-cycle algorithm, Gauss-Seidel relaxation and multigrid optimization. In my test cases this seemed to converge sufficiently quickly, and with good results. I think performance could be much improved with better optimized use of Eigen for my matrix optimizations.

This was done for a university class I took last year, so I probably won't be modifying the code farther. However, I'll be sure to give that paper a read!

Dylan

**Comment by RoyiAvital** [comment]
Hi,
Do you have those implementations in Python / MATLAB?
